index:
    path: /
    controller: App\Controller\HomepageController::index

TricksDetails.show:
    path: /trickdetails
    controller: App\Controller\DetailspageController::show

TricksDetails.edit:
    path: /trickEdition
    controller: App\Controller\DetailspageController::edit