index:
    path: /
    controller: App\Controller\HomepageController::index

Trick.show:
    path: /trick/{trickId}
    controller: App\Controller\TrickController::show

Trick.edit:
    path: /trickEdition/{trickId}
    controller: App\Controller\TrickController::edit

Trick.create:
    path: /trickCreation
    controller: App\Controller\TrickController::create

User.register:
    path: /enregistrement
    controller: App\Controller\RegistrationController::register

User.login:
    path: /connexion
    controller: App\Controller\LoginController::login

User.logout:
    path: /deconnexion
    methods: GET

User.forgot:
    path: /mdpOublie
    controller: App\Controller\UserController::forgot

User.password.reset:
    path: /changerMdp
    controller: App\Controller\UserController::reset

User.verify.email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail

Comments.validation:
    path: /admin/commentsValidation
    controller: App\Controller\CommentsController::index

Comment.validate:
    path: /admin/validateComment/{commentId}
    controller: App\Controller\CommentsController::validate

Comment.delete:
    path: /admin/deleteComment/{commentId}
    controller: App\Controller\CommentsController::delete

Media.create:
    path: /addMedia/{trickId}
    controller: App\Controller\MediaController::create

Media.update:
    path: /updateMedia/{mediaId}
    controller: App\Controller\MediaController::update

Media.delete:
    path: /deleteMedia/{mediaId}
    controller: App\Controller\MediaController::delete