index:
    path: /
    controller: App\Controller\HomepageController::index

Trick.show:
    path: /trick
    controller: App\Controller\TrickController::show

Trick.edit:
    path: /trickEdition
    controller: App\Controller\TrickController::edit

Trick.create:
    path: /trickCreation
    controller: App\Controller\TrickController::create

User.register:
    path: /enregistrement
    controller: App\Controller\RegistrationController::register

User.login:
    path: /connexion
    controller: App\Controller\LoginController::login

User.logout:
    path: /deconnexion
    methods: GET

User.forgot:
    path: /mdpOublie
    controller: App\Controller\UserController::forgot

User.password.reset:
    path: /changerMdp
    controller: App\Controller\UserController::reset

User.verify.email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail